name = input("what is your name? ")
print(name)
color = input("what is your favorite color? ")
animal = input("What is your favorite animal? ")
print("{}, you like a {} {}!".format(name,color,animal))